In [93]:
# Importing necessary modules and libraries
import pandas as pd
import numpy as np

In [94]:
# 
cleaned_dataset = pd.read_csv(f"C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/cleaned_dataset.csv",on_bad_lines = 'skip')

In [95]:
pd.set_option('display.max_columns', 22)

In [96]:
cleaned_dataset.head()

,patient_id,appointment_id,gender,scheduled_date,appointment_date,age,neighbourhood,scholarship,hypertension,diabetes,alcoholism,handicapped,sms_received,no_show,age_category,waiting_days,waiting_days_category,scheduled_month,scheduled_day,appointment_month,appointment_day,no_show_binary
0,2.990000e+13,5642903,F,29/04/2016,29/04/2016,62,JARDIM DA PENHA,0,1,0,0,0,0,No,elderly,0,same day,April,Friday,April,Friday,0
1,5.590000e+14,5642503,M,29/04/2016,29/04/2016,56,JARDIM DA PENHA,0,0,0,0,0,0,No,adult,0,same day,April,Friday,April,Friday,0
2,4.260000e+12,5642549,F,29/04/2016,29/04/2016,62,MATA DA PRAIA,0,0,0,0,0,0,No,elderly,0,same day,April,Friday,April,Friday,0
3,8.680000e+11,5642828,F,29/04/2016,29/04/2016,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,child,0,same day,April,Friday,April,Friday,0
4,8.840000e+12,5642494,F,29/04/2016,29/04/2016,56,JARDIM DA PENHA,0,1,1,0,0,0,No,adult,0,same day,April,Friday,April,Friday,0

In [97]:
cleaned_dataset.shape

(110522, 22)

In [98]:
# Calculation of overall no-show rate
# Yes = 1 means patient didnt show up for the appoinment
# No = 0 means patient did show up for the appointment
total_appointments = cleaned_dataset['appointment_id'].nunique()
total_no_show = cleaned_dataset['no_show_binary'].value_counts().get(1)
total_no_show_rate = (total_no_show / total_appointments) * 100
print(total_appointments)
print(total_no_show)
print(total_no_show_rate)

110522
22314
20.18964550044335

In [99]:
# A new dataframe with count of appointments on the basis of gender
gender_counts = cleaned_dataset.groupby('gender')['appointment_id'].count().reset_index()
gender_counts.columns = ['gender', 'appointments']
gender_counts['gender_share_%'] = (
    gender_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)

In [100]:
gender_counts

  gender  appointments  gender_share_%
0      F         71837            65.0
1      M         38685            35.0

In [101]:
# A new datframe with count of gender wise no_show appointments
gender_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('gender')['appointment_id'].count().reset_index()
gender_noshows.columns = ['gender', 'no_show_count']

In [102]:
gender_noshows

  gender  no_show_count
0      F          14591
1      M           7723

In [103]:
# merging gender_noshows and gender_counts dataframe into a new dataframe
gender_summary = gender_counts.merge(gender_noshows, on='gender')
gender_summary['no_show_rate_%'] = (
    gender_summary['no_show_count'] / gender_summary['appointments'] * 100
).round(2)

In [104]:
gender_summary

  gender  appointments  gender_share_%  no_show_count  no_show_rate_%
0      F         71837            65.0          14591           20.31
1      M         38685            35.0           7723           19.96

In [105]:
gender_summary.to_csv(f"C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/gender_analysis.csv", index = False)

In [106]:
# A new dataframe with count of appointments on the basis of age category
# when age <= 12 then 'child'
# when age > 12 and age < 18 then 'teenager'
# when age >= 18 and age <= 59 then 'adult'
# when age >= 60 then 'elderly'
age_counts = cleaned_dataset.groupby('age_category')['appointment_id'].count().reset_index()
age_counts.columns = ['age_category','appointments']
age_counts['age_share_%'] = (
    age_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)

In [107]:
age_counts

  age_category  appointments  age_share_%
0        adult         61971        56.07
1        child         21036        19.03
2      elderly         21172        19.16
3     teenager          6343         5.74

In [108]:
# A new dataframe with age category based on count of no_show appointments
age_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('age_category')['appointment_id'].count().reset_index()
age_noshows.columns = ['age_category','no_show_count']

In [109]:
age_noshows

  age_category  no_show_count
0        adult          13077
1        child           4306
2      elderly           3241
3     teenager           1690

In [110]:
# Merged age_counts and age_noshows dataframes together into a single dataframe
age_summary = age_counts.merge(age_noshows,on = 'age_category')
age_summary['no_show_rate_%'] = (
    age_summary['no_show_count'] / age_summary['appointments'] * 100
).round(2)

In [111]:
age_summary

  age_category  appointments  age_share_%  no_show_count  no_show_rate_%
0        adult         61971        56.07          13077           21.10
1        child         21036        19.03           4306           20.47
2      elderly         21172        19.16           3241           15.31
3     teenager          6343         5.74           1690           26.64

In [112]:
age_summary.to_csv(f'C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/age_analysis.csv', index = False)

In [113]:
# A new dataframe with the count of appointments based on the days of appointment
day_counts = cleaned_dataset.groupby('appointment_day')['appointment_id'].count().reset_index()
day_counts.columns = ['day_of_week','appointments']
day_counts['day_share_%'] = (
    day_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
day_counts
# Since theres no appointment on Sunday, Sunday doesn't show up

  day_of_week  appointments  day_share_%
0      Friday         19019        17.21
1      Monday         22714        20.55
2    Saturday            39         0.04
3    Thursday         17246        15.60
4     Tuesday         25638        23.20
5   Wednesday         25866        23.40

In [114]:
# A new dataframe with appointment days based on count of no_show appointments
day_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('appointment_day')['appointment_id'].count().reset_index()
day_noshows.columns = ['day_of_week','no_show_count']
day_noshows

  day_of_week  no_show_count
0      Friday           4037
1      Monday           4689
2    Saturday              9
3    Thursday           3337
4     Tuesday           5150
5   Wednesday           5092

In [115]:
# Merged day_counts and day_noshows dataframes together into a single dataframe
day_summary = day_counts.merge(day_noshows, on = 'day_of_week')
day_summary['no_show_rate_%'] = (
    day_summary['no_show_count'] / day_summary['appointments'] * 100 
).round(2)
day_summary

  day_of_week  appointments  day_share_%  no_show_count  no_show_rate_%
0      Friday         19019        17.21           4037           21.23
1      Monday         22714        20.55           4689           20.64
2    Saturday            39         0.04              9           23.08
3    Thursday         17246        15.60           3337           19.35
4     Tuesday         25638        23.20           5150           20.09
5   Wednesday         25866        23.40           5092           19.69

In [116]:
day_summary.to_csv(f'C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/appointment_day_analysis.csv', index = False)

In [117]:
# A new dataframe with count of appointments on the basis of months
month_counts = cleaned_dataset.groupby('appointment_month')['appointment_id'].count().reset_index()
month_counts.columns = ['month','appointments']
month_counts['month_share_%'] = (
    month_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
month_counts
# the data has appointments for only three months - April, June and May

   month  appointments  month_share_%
0  April          3235           2.93
1   June         26451          23.93
2    May         80836          73.14

In [118]:
# A new dataframe with appointment months based on count of no_show appointments
month_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('appointment_month')['appointment_id'].count().reset_index()
month_noshows.columns = ['month','no_show_count']
month_noshows

   month  no_show_count
0  April            633
1   June           4882
2    May          16799

In [119]:
# Merged month_counts and month_noshows dataframes together into a single dataframe
month_summary = month_counts.merge(month_noshows, on = 'month')
month_summary['no_show_rate_%'] = (
    month_summary['no_show_count'] / month_summary['appointments'] * 100
).round(2)
month_summary

   month  appointments  month_share_%  no_show_count  no_show_rate_%
0  April          3235           2.93            633           19.57
1   June         26451          23.93           4882           18.46
2    May         80836          73.14          16799           20.78

In [120]:
month_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/appointment_month_analysis.csv", index = False)

In [121]:
pd.set_option('display.max_rows', 130)

In [122]:
# A new dataframe with count of appointments on the basis of neighbourhood
neighbourhood_counts = cleaned_dataset.groupby('neighbourhood')['appointment_id'].count().reset_index()
neighbourhood_counts.columns = ['neighbourhood','appointments']
neighbourhood_counts['neighbourhood_share_%'] = (
    neighbourhood_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
neighbourhood_counts

                  neighbourhood  appointments  neighbourhood_share_%
0                     AEROPORTO             8                   0.01
1                    ANDORINHAS          2262                   2.05
2               ANTÔNIO HONÓRIO           271                   0.25
3           ARIOVALDO FAVALESSA           282                   0.26
4                BARRO VERMELHO           423                   0.38
5                    BELA VISTA          1907                   1.73
6                BENTO FERREIRA           858                   0.78
7                     BOA VISTA           312                   0.28
8                        BONFIM          2773                   2.51
9                     CARATOÍRA          2565                   2.32
10                       CENTRO          3334                   3.02
11                      COMDUSA           310                   0.28
12                    CONQUISTA           849                   0.77
13                   CONSOLAÇÃO          1375                   1.24
14                   CRUZAMENTO          1398                   1.26
15                     DA PENHA          2217                   2.01
16                   DE LOURDES           305                   0.28
17                    DO CABRAL           560                   0.51
18                   DO MOSCOSO           413                   0.37
19                    DO QUADRO           849                   0.77
20               ENSEADA DO SUÁ           235                   0.21
21                   ESTRELINHA           538                   0.49
22                 FONTE GRANDE           682                   0.62
23               FORTE SÃO JOÃO          1889                   1.71
24                    FRADINHOS           258                   0.23
25                   GOIABEIRAS           700                   0.63
26               GRANDE VITÓRIA          1071                   0.97
27                     GURIGICA          2018                   1.83
28                        HORTO           175                   0.16
29            ILHA DAS CAIEIRAS          1071                   0.97
30          ILHA DE SANTA MARIA          1885                   1.71
31                  ILHA DO BOI            35                   0.03
32                ILHA DO FRADE            10                   0.01
33             ILHA DO PRÍNCIPE          2266                   2.05
34  ILHAS OCEÂNICAS DE TRINDADE             2                   0.00
35                   INHANGUETÁ          1057                   0.96
36                      ITARARÉ          3514                   3.18
37                       JABOUR          2509                   2.27
38               JARDIM CAMBURI          7717                   6.98
39              JARDIM DA PENHA          3877                   3.51
40            JESUS DE NAZARETH          2853                   2.58
41                  JOANA D´ARC          1427                   1.29
42                  JUCUTUQUARA           694                   0.63
43                  MARIA ORTIZ          5805                   5.25
44                      MARUÍPE          1902                   1.72
45                MATA DA PRAIA           644                   0.58
46                   MONTE BELO           824                   0.75
47            MORADA DE CAMBURI            96                   0.09
48               MÁRIO CYPRESTE           371                   0.34
49                     NAZARETH           135                   0.12
50               NOVA PALESTINA          2264                   2.05
51            PARQUE INDUSTRIAL             1                   0.00
52               PARQUE MOSCOSO           802                   0.73
53                      PIEDADE           452                   0.41
54            PONTAL DE CAMBURI            69                   0.06
55               PRAIA DO CANTO          1035                   0.94
56                 PRAIA DO SUÁ          1288                   1.17
57                     REDENÇÃO          1553                   1.41
58                    REPÚBLICA           835                   0.76
59                  RESISTÊNCIA          4430                   4.01
60                        ROMÃO          2215                   2.00
61                SANTA CECÍLIA           448                   0.41
62                  SANTA CLARA           506                   0.46
63                 SANTA HELENA           178                   0.16
64                  SANTA LUÍZA           428                   0.39
65                  SANTA LÚCIA           438                   0.40
66                 SANTA MARTHA          3131                   2.83
67                 SANTA TEREZA          1332                   1.21
68                  SANTO ANDRÉ          2571                   2.33
69                SANTO ANTÔNIO          2744                   2.48
70                SANTOS DUMONT          1276                   1.15
71                  SANTOS REIS           547                   0.49
72             SEGURANÇA DO LAR           145                   0.13
73                 SOLON BORGES           469                   0.42
74                 SÃO BENEDITO          1439                   1.30
75                SÃO CRISTÓVÃO          1836                   1.66
76                     SÃO JOSÉ          1977                   1.79
77                    SÃO PEDRO          2448                   2.21
78                   TABUAZEIRO          3131                   2.83
79                UNIVERSITÁRIO           152                   0.14
80                   VILA RUBIM           851                   0.77

In [123]:
# A new dataframe with count of no show appointments on the basis of neighbourhood
neighbourhood_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('neighbourhood')['appointment_id'].count().reset_index()
neighbourhood_noshows.columns = ['neighbourhood','no_show_count']
neighbourhood_noshows
# by visual inspection i found out, "PARQUE INDUSTRIAL" has only one appointment and the patient showed up so, it isnt listed in the noshows dataframe
# due to which the no of rows has been reduced by 1

                  neighbourhood  no_show_count
0                     AEROPORTO              1
1                    ANDORINHAS            521
2               ANTÔNIO HONÓRIO             50
3           ARIOVALDO FAVALESSA             62
4                BARRO VERMELHO             91
5                    BELA VISTA            384
6                BENTO FERREIRA            193
7                     BOA VISTA             58
8                        BONFIM            550
9                     CARATOÍRA            591
10                       CENTRO            703
11                      COMDUSA             56
12                    CONQUISTA            160
13                   CONSOLAÇÃO            236
14                   CRUZAMENTO            304
15                     DA PENHA            429
16                   DE LOURDES             47
17                    DO CABRAL             88
18                   DO MOSCOSO             92
19                    DO QUADRO            140
20               ENSEADA DO SUÁ             52
21                   ESTRELINHA            106
22                 FONTE GRANDE            149
23               FORTE SÃO JOÃO            346
24                    FRADINHOS             48
25                   GOIABEIRAS            137
26               GRANDE VITÓRIA            217
27                     GURIGICA            456
28                        HORTO             42
29            ILHA DAS CAIEIRAS            235
30          ILHA DE SANTA MARIA            361
31                  ILHA DO BOI              3
32                ILHA DO FRADE              2
33             ILHA DO PRÍNCIPE            532
34  ILHAS OCEÂNICAS DE TRINDADE              2
35                   INHANGUETÁ            202
36                      ITARARÉ            923
37                       JABOUR            451
38               JARDIM CAMBURI           1465
39              JARDIM DA PENHA            631
40            JESUS DE NAZARETH            696
41                  JOANA D´ARC            258
42                  JUCUTUQUARA            133
43                  MARIA ORTIZ           1219
44                      MARUÍPE            424
45                MATA DA PRAIA            110
46                   MONTE BELO            166
47            MORADA DE CAMBURI             16
48               MÁRIO CYPRESTE             54
49                     NAZARETH             29
50               NOVA PALESTINA            402
51               PARQUE MOSCOSO            179
52                      PIEDADE             88
53            PONTAL DE CAMBURI             12
54               PRAIA DO CANTO            190
55                 PRAIA DO SUÁ            294
56                     REDENÇÃO            275
57                    REPÚBLICA            143
58                  RESISTÊNCIA            905
59                        ROMÃO            474
60                SANTA CECÍLIA            123
61                  SANTA CLARA            134
62                 SANTA HELENA             37
63                  SANTA LUÍZA             77
64                  SANTA LÚCIA             86
65                 SANTA MARTHA            496
66                 SANTA TEREZA            272
67                  SANTO ANDRÉ            508
68                SANTO ANTÔNIO            482
69                SANTOS DUMONT            369
70                  SANTOS REIS            112
71             SEGURANÇA DO LAR             28
72                 SOLON BORGES             69
73                 SÃO BENEDITO            287
74                SÃO CRISTÓVÃO            363
75                     SÃO JOSÉ            428
76                    SÃO PEDRO            515
77                   TABUAZEIRO            572
78                UNIVERSITÁRIO             32
79                   VILA RUBIM            141

In [124]:
# Merged neighbourhood_counts and neighbourhood_noshows into a single dataframe
neighbourhood_summary = neighbourhood_counts.merge(neighbourhood_noshows, on = 'neighbourhood')
neighbourhood_summary['no_show_rate_%'] = (
    neighbourhood_summary['no_show_count'] / neighbourhood_summary['appointments'] * 100
).round(2)
neighbourhood_summary

,neighbourhood,appointments,neighbourhood_share_%,no_show_count,no_show_rate_%
0,AEROPORTO,8,0.01,1,12.50
1,ANDORINHAS,2262,2.05,521,23.03
2,ANTÔNIO HONÓRIO,271,0.25,50,18.45
3,ARIOVALDO FAVALESSA,282,0.26,62,21.99
4,BARRO VERMELHO,423,0.38,91,21.51
5,BELA VISTA,1907,1.73,384,20.14
6,BENTO FERREIRA,858,0.78,193,22.49
7,BOA VISTA,312,0.28,58,18.59
8,BONFIM,2773,2.51,550,19.83
9,CARATOÍRA,2565,2.32,591,23.04
10,CENTRO,3334,3.02,703,21.09
11,COMDUSA,310,0.28,56,18.06
12,CONQUISTA,849,0.77,160,18.85
13,CONSOLAÇÃO,1375,1.24,236,17.16
14,CRUZAMENTO,1398,1.26,304,21.75
15,DA PENHA,2217,2.01,429,19.35
16,DE LOURDES,305,0.28,47,15.41
17,DO CABRAL,560,0.51,88,15.71
18,DO MOSCOSO,413,0.37,92,22.28
19,DO QUADRO,849,0.77,140,16.49
20,ENSEADA DO SUÁ,235,0.21,52,22.13
21,ESTRELINHA,538,0.49,106,19.70
22,FONTE GRANDE,682,0.62,149,21.85
23,FORTE SÃO JOÃO,1889,1.71,346,18.32
24,FRADINHOS,258,0.23,48,18.60
25,GOIABEIRAS,700,0.63,137,19.57
26,GRANDE VITÓRIA,1071,0.97,217,20.26
27,GURIGICA,2018,1.83,456,22.60
28,HORTO,175,0.16,42,24.00
29,ILHA DAS CAIEIRAS,1071,0.97,235,21.94
30,ILHA DE SANTA MARIA,1885,1.71,361,19.15
31,ILHA DO BOI,35,0.03,3,8.57
32,ILHA DO FRADE,10,0.01,2,20.00
33,ILHA DO PRÍNCIPE,2266,2.05,532,23.48
34,ILHAS OCEÂNICAS DE TRINDADE,2,0.00,2,100.00
35,INHANGUETÁ,1057,0.96,202,19.11
36,ITARARÉ,3514,3.18,923,26.27
37,JABOUR,2509,2.27,451,17.98
38,JARDIM CAMBURI,7717,6.98,1465,18.98
39,JARDIM DA PENHA,3877,3.51,631,16.28
40,JESUS DE NAZARETH,2853,2.58,696,24.40
41,JOANA D´ARC,1427,1.29,258,18.08
42,JUCUTUQUARA,694,0.63,133,19.16
43,MARIA ORTIZ,5805,5.25,1219,21.00
44,MARUÍPE,1902,1.72,424,22.29
45,MATA DA PRAIA,644,0.58,110,17.08
46,MONTE BELO,824,0.75,166,20.15
47,MORADA DE CAMBURI,96,0.09,16,16.67
48,MÁRIO CYPRESTE,371,0.34,54,14.56
49,NAZARETH,135,0.12,29,21.48
50,NOVA PALESTINA,2264,2.05,402,17.76
51,PARQUE MOSCOSO,802,0.73,179,22.32
52,PIEDADE,452,0.41,88,19.47
53,PONTAL DE CAMBURI,69,0.06,12,17.39
54,PRAIA DO CANTO,1035,0.94,190,18.36
55,PRAIA DO SUÁ,1288,1.17,294,22.83
56,REDENÇÃO,1553,1.41,275,17.71
57,REPÚBLICA,835,0.76,143,17.13
58,RESISTÊNCIA,4430,4.01,905,20.43
59,ROMÃO,2215,2.00,474,21.40
60,SANTA CECÍLIA,448,0.41,123,27.46
61,SANTA CLARA,506,0.46,134,26.48
62,SANTA HELENA,178,0.16,37,20.79
63,SANTA LUÍZA,428,0.39,77,17.99
64,SANTA LÚCIA,438,0.40,86,19.63
65,SANTA MARTHA,3131,2.83,496,15.84
66,SANTA TEREZA,1332,1.21,272,20.42
67,SANTO ANDRÉ,2571,2.33,508,19.76
68,SANTO ANTÔNIO,2744,2.48,482,17.57
69,SANTOS DUMONT,1276,1.15,369,28.92
70,SANTOS REIS,547,0.49,112,20.48
71,SEGURANÇA DO LAR,145,0.13,28,19.31
72,SOLON BORGES,469,0.42,69,14.71
73,SÃO BENEDITO,1439,1.30,287,19.94
74,SÃO CRISTÓVÃO,1836,1.66,363,19.77
75,SÃO JOSÉ,1977,1.79,428,21.65
76,SÃO PEDRO,2448,2.21,515,21.04
77,TABUAZEIRO,3131,2.83,572,18.27
78,UNIVERSITÁRIO,152,0.14,32,21.05
79,VILA RUBIM,851,0.77,141,16.57

In [125]:
neighbourhood_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/neighbourhood_analysis.csv", index = False, encoding = 'utf-8-sig')

In [126]:
# A new dataframe with count of appointments on the basis of scholarship ( 0 means no scholarship, 1 means scholarship)
scholarship_counts = cleaned_dataset.groupby('scholarship')['appointment_id'].count().reset_index()
scholarship_counts.columns = ['scholarship','appointments']
scholarship_counts['scholarship_share_%'] = (
    scholarship_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
scholarship_counts

   scholarship  appointments  scholarship_share_%
0            0         99661                90.17
1            1         10861                 9.83

In [127]:
# A new dataframe with count of no show appointments on the basis of scholarship
scholarship_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('scholarship')['appointment_id'].count().reset_index()
scholarship_noshows.columns = ['scholarship','no_show_count']
scholarship_noshows

   scholarship  no_show_count
0            0          19736
1            1           2578

In [128]:
# Merged scholarship_counts with scholarship_noshows into a single dataframe
scholarship_summary = scholarship_counts.merge(scholarship_noshows, on = 'scholarship')
scholarship_summary['no_show_rate_%'] = (
    scholarship_summary['no_show_count'] / scholarship_summary['appointments'] * 100
).round(2)
scholarship_summary

,scholarship,appointments,scholarship_share_%,no_show_count,no_show_rate_%
0,0,99661,90.17,19736,19.80
1,1,10861,9.83,2578,23.74

In [129]:
scholarship_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/scholarship_analysis.csv", index= False)

In [130]:
# A new dataframe with count of appointments on the basis of scholarship ( 0 means no hypertension, 1 means hypertension)
hypertension_counts = cleaned_dataset.groupby('hypertension')['appointment_id'].count().reset_index()
hypertension_counts.columns = ['hypertension','appointments']
hypertension_counts['hypertension_share_%'] = (
    hypertension_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
hypertension_counts

   hypertension  appointments  hypertension_share_%
0             0         88721                 80.27
1             1         21801                 19.73

In [131]:
# A new dataframe with count of no show appointments on the basis of hypertension
hypertension_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('hypertension')['appointment_id'].count().reset_index()
hypertension_noshows.columns = ['hypertension','no_show_count']
hypertension_noshows

   hypertension  no_show_count
0             0          18542
1             1           3772

In [132]:
# Merged hypertension_counts with hypertension_noshows into a single dataframe
hypertension_summary = hypertension_counts.merge(hypertension_noshows, on = 'hypertension')
hypertension_summary['no_show_rate_%'] = (
    hypertension_summary['no_show_count'] / hypertension_summary['appointments'] * 100
).round(2)
hypertension_summary

,hypertension,appointments,hypertension_share_%,no_show_count,no_show_rate_%
0,0,88721,80.27,18542,20.9
1,1,21801,19.73,3772,17.3

In [133]:
hypertension_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/hypertension_analysis.csv", index= False)

In [134]:
# A new dataframe with count of appointments on the basis of diabetes ( 0 means no diabetes, 1 means diabetes)
diabetes_counts = cleaned_dataset.groupby('diabetes')['appointment_id'].count().reset_index()
diabetes_counts.columns = ['diabetes','appointments']
diabetes_counts['diabetes_share_%'] = (
    diabetes_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
diabetes_counts

   diabetes  appointments  diabetes_share_%
0         0        102579             92.81
1         1          7943              7.19

In [135]:
# A new dataframe with count of no show appointments on the basis of diabetes
diabetes_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('diabetes')['appointment_id'].count().reset_index()
diabetes_noshows.columns = ['diabetes','no_show_count']
diabetes_noshows

   diabetes  no_show_count
0         0          20884
1         1           1430

In [136]:
# Merged diabetes_counts with diabetes_noshows into a single dataframe
diabetes_summary = diabetes_counts.merge(diabetes_noshows, on = 'diabetes')
diabetes_summary['no_show_rate_%'] = (
    diabetes_summary['no_show_count'] / diabetes_summary['appointments'] * 100
).round(2)
diabetes_summary

   diabetes  appointments  diabetes_share_%  no_show_count  no_show_rate_%
0         0        102579             92.81          20884           20.36
1         1          7943              7.19           1430           18.00

In [137]:
diabetes_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/diabetes_analysis.csv", index= False)

In [138]:
# A new dataframe with count of appointments on the basis of alcoholism ( 0 means no alcoholism, 1 means alcoholism)
alcoholism_counts = cleaned_dataset.groupby('alcoholism')['appointment_id'].count().reset_index()
alcoholism_counts.columns = ['alcoholism','appointments']
alcoholism_counts['alcoholism_share_%'] = (
    alcoholism_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
alcoholism_counts

   alcoholism  appointments  alcoholism_share_%
0           0        107162               96.96
1           1          3360                3.04

In [139]:
# A new dataframe with count of no show appointments on the basis of alcoholism
alcoholism_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('alcoholism')['appointment_id'].count().reset_index()
alcoholism_noshows.columns = ['alcoholism','no_show_count']
alcoholism_noshows

   alcoholism  no_show_count
0           0          21637
1           1            677

In [140]:
# Merged alcoholism_counts with alcoholism_noshows into a single dataframe
alcoholism_summary = alcoholism_counts.merge(alcoholism_noshows, on = 'alcoholism')
alcoholism_summary['no_show_rate_%'] = (
    alcoholism_summary['no_show_count'] / alcoholism_summary['appointments'] * 100
).round(2)
alcoholism_summary

   alcoholism  appointments  alcoholism_share_%  no_show_count  no_show_rate_%
0           0        107162               96.96          21637           20.19
1           1          3360                3.04            677           20.15

In [141]:
alcoholism_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/alcoholism_analysis.csv", index= False)

In [142]:
# A new dataframe with count of appointments on the basis of handicapped ( 0 means no handicapped, 1 means handicapped)
handicapped_counts = cleaned_dataset.groupby('handicapped')['appointment_id'].count().reset_index()
handicapped_counts.columns = ['handicapped','appointments']
handicapped_counts['handicapped_share_%'] = (
    handicapped_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
handicapped_counts

   handicapped  appointments  handicapped_share_%
0            0        108283                97.97
1            1          2239                 2.03

In [143]:
# A new dataframe with count of no show appointments on the basis of handicapped
handicapped_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('handicapped')['appointment_id'].count().reset_index()
handicapped_noshows.columns = ['handicapped','no_show_count']
handicapped_noshows

   handicapped  no_show_count
0            0          21909
1            1            405

In [144]:
# Merged handicapped_counts with handicapped_noshows into a single dataframe
handicapped_summary = handicapped_counts.merge(handicapped_noshows, on = 'handicapped')
handicapped_summary['no_show_rate_%'] = (
   handicapped_summary['no_show_count'] / handicapped_summary['appointments'] * 100
).round(2)
handicapped_summary

,handicapped,appointments,handicapped_share_%,no_show_count,no_show_rate_%
0,0,108283,97.97,21909,20.23
1,1,2239,2.03,405,18.09

In [145]:
handicapped_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/handicapped_analysis.csv", index= False)

In [146]:
# A new dataframe with count of appointments on the basis of sms_received ( 0 means no sms_received, 1 means sms_received)
sms_received_counts = cleaned_dataset.groupby('sms_received')['appointment_id'].count().reset_index()
sms_received_counts.columns = ['sms_received','appointments']
sms_received_counts['sms_received_share_%'] = (
    sms_received_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
sms_received_counts

   sms_received  appointments  sms_received_share_%
0             0         75040                  67.9
1             1         35482                  32.1

In [147]:
# A new dataframe with count of no show appointments on the basis of sms_received
sms_received_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('sms_received')['appointment_id'].count().reset_index()
sms_received_noshows.columns = ['sms_received','no_show_count']
sms_received_noshows

   sms_received  no_show_count
0             0          12530
1             1           9784

In [148]:
# Merged sms_received_counts with sms_received_noshows into a single dataframe
sms_received_summary = sms_received_counts.merge(sms_received_noshows, on = 'sms_received')
sms_received_summary['no_show_rate_%'] = (
   sms_received_summary['no_show_count'] / sms_received_summary['appointments'] * 100
).round(2)
sms_received_summary

,sms_received,appointments,sms_received_share_%,no_show_count,no_show_rate_%
0,0,75040,67.9,12530,16.70
1,1,35482,32.1,9784,27.57

In [149]:
sms_received_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/sms_received_analysis.csv", index= False)

In [151]:
# Among the patients who received the sms how many patients didint show up?
no_show_after_sms = cleaned_dataset[cleaned_dataset['sms_received'] == 1].groupby('no_show_binary')['appointment_id'].count().reset_index()
no_show_after_sms.columns = ['no_show_binary','no_show_count']
no_show_after_sms['no_show_after_sms_received_%'] = (
    no_show_after_sms['no_show_count'] / sms_received_summary.loc[1,'appointments'] * 100
).round(2)
no_show_after_sms

   no_show_binary  no_show_count  no_show_after_sms_received_%
0               0          25698                         72.43
1               1           9784                         27.57

In [152]:
# Statistics for waiitng days for patients who received sms and patients who didn't
sms_waiting_days = cleaned_dataset.groupby('sms_received')['waiting_days'].agg(
    count = 'count',
    mean_waiting_days = 'mean',
    median_waiting_days = 'median',
    std_waiting_days = 'std'
).round(5).reset_index()

sms_waiting_days['sms_received'] = sms_waiting_days['sms_received'].map({
    0: 'No SMS', 
    1: 'SMS Received'
})
sms_waiting_days

,sms_received,count,mean_waiting_days,median_waiting_days,std_waiting_days
0,No SMS,75040,6.00790,0.0,12.33376
1,SMS Received,35482,19.01671,14.0,16.97872

In [153]:
# Statistics for all the combiantions of values in sms_received and waiting_days_category
sms_waiting_days_category = cleaned_dataset.groupby(['sms_received','waiting_days_category'])['waiting_days'].agg(
    appointments_count = 'count',
    mean_waiting_days = 'mean',
    median_waiting_days = 'median',
    std_waiting_days = 'std'
).round(2).reset_index()

sms_waiting_days_category['sms_received'] = sms_waiting_days_category['sms_received'].map({
    0: 'No SMS', 
    1: 'SMS Received'
})
sms_waiting_days_category

,sms_received,waiting_days_category,appointments_count,mean_waiting_days,median_waiting_days,std_waiting_days
0,No SMS,long wait,3968,46.19,39.0,18.27
1,No SMS,same day,38563,0.00,0.0,0.00
2,No SMS,within a month,11872,17.34,16.0,6.50
3,No SMS,within a week,20637,2.99,2.0,1.97
4,SMS Received,long wait,6410,47.15,41.0,18.31
5,SMS Received,within a month,17524,17.76,17.0,6.71
6,SMS Received,within a week,11548,5.30,5.0,1.31

In [154]:
# A new dataframe with the no_show count and percentage on the basis of waiting_days_category and sms_received?
sms_no_show = cleaned_dataset.groupby(['waiting_days_category','sms_received']).agg(
    count = ('appointment_id', 'count'),
    no_show = ('no_show_binary', 'sum')
).reset_index()
sms_no_show['no_show_%'] = (
    sms_no_show['no_show'] / sms_no_show['count'] * 100
).round(2)

sms_no_show['sms_received'] = sms_no_show['sms_received'].map({
    0: 'No SMS', 
    1: 'SMS Received'
})
sms_no_show

  waiting_days_category  sms_received  count  no_show  no_show_%
0             long wait        No SMS   3968     1489      37.53
1             long wait  SMS Received   6410     1936      30.20
2              same day        No SMS  38563     1792       4.65
3        within a month        No SMS  11872     4221      35.55
4        within a month  SMS Received  17524     5104      29.13
5         within a week        No SMS  20637     5028      24.36
6         within a week  SMS Received  11548     2744      23.76

In [155]:
sms_no_show.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/sms_and_waiting_days_correlation.csv", index= False)

In [156]:
# A new dataframe with count of appointments on the basis of waiting days
waiting_days_counts = cleaned_dataset.groupby('waiting_days')['appointment_id'].count().reset_index()
waiting_days_counts.columns = ['waiting_days','appointments']
waiting_days_counts['waiting_days_share_%'] = (
    waiting_days_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
waiting_days_counts

     waiting_days  appointments  waiting_days_share_%
0               0         38563                 34.89
1               1          5213                  4.72
2               2          6725                  6.08
3               3          2737                  2.48
4               4          5290                  4.79
5               5          3277                  2.97
6               6          4037                  3.65
7               7          4906                  4.44
8               8          2332                  2.11
9               9          1605                  1.45
10             10          1391                  1.26
11             11           987                  0.89
12             12          1115                  1.01
13             13          1682                  1.52
14             14          2913                  2.64
15             15          1503                  1.36
16             16          1151                  1.04
17             17          1107                  1.00
18             18          1021                  0.92
19             19          1044                  0.94
20             20          1187                  1.07
21             21          1861                  1.68
22             22          1173                  1.06
23             23           822                  0.74
24             24           622                  0.56
25             25           637                  0.58
26             26           731                  0.66
27             27          1013                  0.92
28             28          1706                  1.54
29             29          1089                  0.99
30             30           704                  0.64
31             31           672                  0.61
32             32           586                  0.53
33             33           664                  0.60
34             34           808                  0.73
35             35           963                  0.87
36             36           551                  0.50
37             37           331                  0.30
38             38           199                  0.18
39             39           170                  0.15
40             40           254                  0.23
41             41           342                  0.31
42             42           417                  0.38
43             43           254                  0.23
44             44           157                  0.14
45             45           137                  0.12
46             46           121                  0.11
47             47           109                  0.10
48             48           117                  0.11
49             49           216                  0.20
50             50           182                  0.16
51             51            91                  0.08
52             52            90                  0.08
53             53            96                  0.09
54             54            73                  0.07
55             55           109                  0.10
56             56           203                  0.18
57             57            98                  0.09
58             58           110                  0.10
59             59            90                  0.08
60             60            73                  0.07
61             61           135                  0.12
62             62           193                  0.17
63             63           200                  0.18
64             64            75                  0.07
65             65            97                  0.09
66             66           162                  0.15
67             67            63                  0.06
68             68            70                  0.06
69             69           105                  0.10
70             70           112                  0.10
71             71            50                  0.05
72             72            53                  0.05
73             73            37                  0.03
74             74            39                  0.04
75             75            72                  0.07
76             76            65                  0.06
77             77            53                  0.05
78             78            33                  0.03
79             79            23                  0.02
80             80            18                  0.02
81             81            10                  0.01
82             82             1                  0.00
83             83             8                  0.01
84             84            54                  0.05
85             85            37                  0.03
86             86             6                  0.01
87             87            16                  0.01
88             88            16                  0.01
89             89            17                  0.02
90             90            58                  0.05
91             91            56                  0.05
92             92             3                  0.00
93             93             2                  0.00
94             94             2                  0.00
95             95             5                  0.00
96             96             4                  0.00
97             97             2                  0.00
98             98             5                  0.00
99            101             1                  0.00
100           102             4                  0.00
101           103             5                  0.00
102           104             8                  0.01
103           105             4                  0.00
104           107             2                  0.00
105           108             5                  0.00
106           109             5                  0.00
107           110             2                  0.00
108           111             5                  0.00
109           112             5                  0.00
110           115             2                  0.00
111           117             1                  0.00
112           119             4                  0.00
113           122             3                  0.00
114           123             1                  0.00
115           125             1                  0.00
116           126             1                  0.00
117           127             1                  0.00
118           132             1                  0.00
119           133            11                  0.01
120           139             1                  0.00
121           142             8                  0.01
122           146             1                  0.00
123           151             1                  0.00
124           155            10                  0.01
125           162            11                  0.01
126           169             8                  0.01
127           176            16                  0.01
128           179            10                  0.01

In [157]:
# A new dataframe with count of no show appointments on the basis of waiting days
waiting_days_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('waiting_days')['appointment_id'].count().reset_index()
waiting_days_noshows.columns = ['waiting_days','no_show_count']
waiting_days_noshows

     waiting_days  no_show_count
0               0           1792
1               1           1113
2               2           1602
3               3            644
4               4           1231
5               5            872
6               6           1001
7               7           1309
8               8            670
9               9            440
10             10            440
11             11            312
12             12            353
13             13            536
14             14            913
15             15            502
16             16            351
17             17            350
18             18            312
19             19            363
20             20            408
21             21            575
22             22            404
23             23            276
24             24            235
25             25            256
26             26            263
27             27            320
28             28            503
29             29            356
30             30            187
31             31            220
32             32            206
33             33            222
34             34            270
35             35            359
36             36            171
37             37            119
38             38             68
39             39             55
40             40            103
41             41            121
42             42            154
43             43             76
44             44             47
45             45             50
46             46             44
47             47             33
48             48             34
49             49             75
50             50             49
51             51             33
52             52             23
53             53             33
54             54             27
55             55             49
56             56             51
57             57             37
58             58             36
59             59             33
60             60             31
61             61             31
62             62             40
63             63             53
64             64             28
65             65             29
66             66             48
67             67             19
68             68             23
69             69             34
70             70             35
71             71             11
72             72             16
73             73             13
74             74             13
75             75             22
76             76             20
77             77             18
78             78             13
79             79              9
80             80              8
81             81              4
82             83              1
83             84             12
84             85              8
85             86              1
86             87              5
87             88              5
88             89              7
89             90             14
90             91             12
91             95              1
92             96              1
93             98              1
94            102              1
95            103              3
96            104              6
97            110              1
98            111              1
99            126              1
100           132              1
101           133              4
102           139              1
103           142              3
104           146              1
105           151              1
106           155              6
107           162              2
108           169              1
109           176              6
110           179              2

In [158]:
# Merged waiting_days_counts with waiitng_days_noshows into a single dataframe
waiting_days_summary = waiting_days_counts.merge(waiting_days_noshows, on = 'waiting_days')
waiting_days_summary['no_show_rate_%'] = (
   waiting_days_summary['no_show_count'] / waiting_days_summary['appointments'] * 100
).round(2)
waiting_days_summary

,waiting_days,appointments,waiting_days_share_%,no_show_count,no_show_rate_%
0,0,38563,34.89,1792,4.65
1,1,5213,4.72,1113,21.35
2,2,6725,6.08,1602,23.82
3,3,2737,2.48,644,23.53
4,4,5290,4.79,1231,23.27
5,5,3277,2.97,872,26.61
6,6,4037,3.65,1001,24.80
7,7,4906,4.44,1309,26.68
8,8,2332,2.11,670,28.73
9,9,1605,1.45,440,27.41
10,10,1391,1.26,440,31.63
11,11,987,0.89,312,31.61
12,12,1115,1.01,353,31.66
13,13,1682,1.52,536,31.87
14,14,2913,2.64,913,31.34
15,15,1503,1.36,502,33.40
16,16,1151,1.04,351,30.50
17,17,1107,1.00,350,31.62
18,18,1021,0.92,312,30.56
19,19,1044,0.94,363,34.77
20,20,1187,1.07,408,34.37
21,21,1861,1.68,575,30.90
22,22,1173,1.06,404,34.44
23,23,822,0.74,276,33.58
24,24,622,0.56,235,37.78
25,25,637,0.58,256,40.19
26,26,731,0.66,263,35.98
27,27,1013,0.92,320,31.59
28,28,1706,1.54,503,29.48
29,29,1089,0.99,356,32.69
30,30,704,0.64,187,26.56
31,31,672,0.61,220,32.74
32,32,586,0.53,206,35.15
33,33,664,0.60,222,33.43
34,34,808,0.73,270,33.42
35,35,963,0.87,359,37.28
36,36,551,0.50,171,31.03
37,37,331,0.30,119,35.95
38,38,199,0.18,68,34.17
39,39,170,0.15,55,32.35
40,40,254,0.23,103,40.55
41,41,342,0.31,121,35.38
42,42,417,0.38,154,36.93
43,43,254,0.23,76,29.92
44,44,157,0.14,47,29.94
45,45,137,0.12,50,36.50
46,46,121,0.11,44,36.36
47,47,109,0.10,33,30.28
48,48,117,0.11,34,29.06
49,49,216,0.20,75,34.72
50,50,182,0.16,49,26.92
51,51,91,0.08,33,36.26
52,52,90,0.08,23,25.56
53,53,96,0.09,33,34.38
54,54,73,0.07,27,36.99
55,55,109,0.10,49,44.95
56,56,203,0.18,51,25.12
57,57,98,0.09,37,37.76
58,58,110,0.10,36,32.73
59,59,90,0.08,33,36.67
60,60,73,0.07,31,42.47
61,61,135,0.12,31,22.96
62,62,193,0.17,40,20.73
63,63,200,0.18,53,26.50
64,64,75,0.07,28,37.33
65,65,97,0.09,29,29.90
66,66,162,0.15,48,29.63
67,67,63,0.06,19,30.16
68,68,70,0.06,23,32.86
69,69,105,0.10,34,32.38
70,70,112,0.10,35,31.25
71,71,50,0.05,11,22.00
72,72,53,0.05,16,30.19
73,73,37,0.03,13,35.14
74,74,39,0.04,13,33.33
75,75,72,0.07,22,30.56
76,76,65,0.06,20,30.77
77,77,53,0.05,18,33.96
78,78,33,0.03,13,39.39
79,79,23,0.02,9,39.13
80,80,18,0.02,8,44.44
81,81,10,0.01,4,40.00
82,83,8,0.01,1,12.50
83,84,54,0.05,12,22.22
84,85,37,0.03,8,21.62
85,86,6,0.01,1,16.67
86,87,16,0.01,5,31.25
87,88,16,0.01,5,31.25
88,89,17,0.02,7,41.18
89,90,58,0.05,14,24.14
90,91,56,0.05,12,21.43
91,95,5,0.00,1,20.00
92,96,4,0.00,1,25.00
93,98,5,0.00,1,20.00
94,102,4,0.00,1,25.00
95,103,5,0.00,3,60.00
96,104,8,0.01,6,75.00
97,110,2,0.00,1,50.00
98,111,5,0.00,1,20.00
99,126,1,0.00,1,100.00
100,132,1,0.00,1,100.00
101,133,11,0.01,4,36.36
102,139,1,0.00,1,100.00
103,142,8,0.01,3,37.50
104,146,1,0.00,1,100.00
105,151,1,0.00,1,100.00
106,155,10,0.01,6,60.00
107,162,11,0.01,2,18.18
108,169,8,0.01,1,12.50
109,176,16,0.01,6,37.50
110,179,10,0.01,2,20.00

In [159]:
waiting_days_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/waiting_days_analysis.csv", index= False)

In [160]:
# A new dataframe with count of appointments on the basis of waiting days category
waiting_days_category_counts = cleaned_dataset.groupby('waiting_days_category')['appointment_id'].count().reset_index()
waiting_days_category_counts.columns = ['waiting_days_category','appointments']
waiting_days_counts['waiting_days_category_share_%'] = (
    waiting_days_category_counts['appointments'] / len(cleaned_dataset) * 100
).round(2)
waiting_days_category_counts

  waiting_days_category  appointments
0             long wait         10378
1              same day         38563
2        within a month         29396
3         within a week         32185

In [161]:
# A new dataframe with count of no show appointments on the basis of waiting days category
waiting_days_category_noshows = cleaned_dataset[cleaned_dataset['no_show_binary'] == 1].groupby('waiting_days_category')['appointment_id'].count().reset_index()
waiting_days_category_noshows.columns = ['waiting_days_category','no_show_count']
waiting_days_category_noshows

  waiting_days_category  no_show_count
0             long wait           3425
1              same day           1792
2        within a month           9325
3         within a week           7772

In [162]:
# Merged waiting_days_category_counts with waiitng_days_category_noshows into a single dataframe
waiting_days_category_summary = waiting_days_category_counts.merge(waiting_days_category_noshows, on = 'waiting_days_category')
waiting_days_category_summary['no_show_rate_%'] = (
   waiting_days_category_summary['no_show_count'] / waiting_days_category_summary['appointments'] * 100
).round(2)
waiting_days_category_summary

  waiting_days_category  appointments  no_show_count  no_show_rate_%
0             long wait         10378           3425           33.00
1              same day         38563           1792            4.65
2        within a month         29396           9325           31.72
3         within a week         32185           7772           24.15

In [163]:
waiting_days_category_summary.to_csv("C:/Users/Acer/Desktop/intern_apply_projects/no show medical data analysis/csv files/waiting_days_category_analysis.csv", index= False)